name = "cloudflare-workers"
type = "webpack"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-17"

[vars]
UPSTASH_KAFKA_REST_URL=""
UPSTASH_KAFKA_REST_USERNAME=""
UPSTASH_KAFKA_REST_PASSWORD=""
